# Introduction to Python
*Space-Time Analytics — Lecture 2b*

* **Prof. Carson J. Q. Farmer**  
    <i class="fa-fw fa fa-twitter"></i> [@carsonfarmer](https://twitter.com/carsonfarmer)  
    <i class="fa-fw fa fa-globe"></i> [carsonfarmer.com](https://carsonfarmer.com)  
    <i class="fa-fw fa fa-envelope-o"></i> [carson.farmer@colorado.edu](mailto:carson.farmer@colorado.edu)  
    <i class="fa-fw fa fa-github-alt"></i> [github.com/carsonfarmer](https://github.com/carsonfarmer)  
    <i class="fa-fw fa fa-briefcase"></i> Guggenheim Building Room 207  
    <i class="fa-fw fa fa-clock-o"></i> Wednesdays 2:00-3:00 PM and 4:15-5:15 PM  

## Introduction

To use the powerful range of tools, functions, commands, and spatial libraries available in `Python`, you first need to learn a little bit about the syntax and meaning of `Python` commands. Once you have learned this, operations become simple to perform...

## Invoking an Operation

Complex computations are built up from simpler computations. This may seem obvious, but it is a powerful idea. An **algorithm** is just a description of a computation in terms of other computations that you already know how to perform. To help distinguish between the computation as a whole and the simpler parts, it is helpful to introduce a new word: an **operator** performs a computation.

It's helpful to think of the computation carried out by an operator as involving four parts:

1. The name of the operator
2. The input arguments
3. The output value
4. Side effects

## Inputs and Outputs

A typical operation takes one or more **input arguments** and uses the information in these to produce an **output value**.

Along the way, the computer might take some action: display a graph, store a file, make a sound, etc. These actions are called **side effects**.

Since `Python` is a general-purpose programming language, we usually need to `import` special packages for doing specific things (like working with spatial data). You can think of this as adding words to the language. For *Scientific `Python`*, the most important library that we need is `numpy` (*Numerical Python*), which can be loaded like this:

In [34]:
import numpy as np  # Importing numpy 'as' np is just to reduce typing...

## Syntax

To tell the computer to perform a computation — call this **invoking an operation** or giving a **command** — you need to provide the name and the input arguments in a specific format. The computer then returns the output value.

For example, the command `np.sqrt(25)` invokes the square root operator (named `sqrt` from the `numpy` library) on the argument `25`. The output from the computation will, of course, be `5`.

The syntax of invoking an operation consists of the operator's name, followed by round parentheses. The input arguments go inside the parentheses.

* The software program that you use to invoke operators is called an **interpreter**\*
* You enter your commands as a 'dialog' between you and the interpreter
* Commands can be entered as part of a 'script', directly at a 'command prompt' or within a `Notebook` like we're doing now:

In [37]:
np.median(np.arange(1, 10))

5.0

<div class="alert alert-info" style="font-size: .8em;">
The interpreter is the program you are running in the background when you start a `Python` `Notebook`
</div>

* In the previous situation, the 'prompt' is `In [3]:`, and the 'command' is `np.sqrt(25)`.
* When you press '⌘/Ctrl + Return', the interpreter reads your command and performs the computation.
* For commands such as the one above, the interpreter will print the output value from the computation.

## Arguments 

Often, operations involve more than one argument. The various arguments are separated by commas. For example, here is an operation named `arange` from the `numpy` library that produces 'a range' of numbers (increasing values between 3 and 10):

In [59]:
np.sqrt(x)

4.0

In [58]:
np.mean(np.random.normal(size=)

0.17629237645606133

## Order of Arguments

In the previous example, the first argument tells where to start the range and the second tells where to end it. The order of the arguments is important. For instance, *here* is the range produced when 10 is the first argument, 3 is the second, and the third is -1 (decreasing values between 10 and 3):

In [44]:
np.arange(10, 3, -1)

array([10,  9,  8,  7,  6,  5,  4])

## Named Arguments

For some operators, particularly those that have many input arguments, some of the arguments can be referred to by name rather than position. This is particularly useful when the named argument has a sensible default value. For example, the `arange` operator from the `numpy` library can be instructed what type of output values to produce (integers, floats, etc). This is accomplished using an argument named `dtype`:

In [49]:
10/3

3.3333333333333335

## No Arguments

Note that all the values in the range now have decimal places. Depending on the circumstances, all four parts of an operation need not be present. For example, the `ctime` operation from the `time` library returns the current time and date; no input arguments are required:

In [50]:
import time
time.ctime()

'Mon Aug 29 13:24:45 2016'

<div class="alert alert-info" style="font-size: .8em;">
In the previous example, we first imported the `time` library, which provides a series of commands that help us work with dates and times. Next, even though there are no arguments, the parentheses are still used when calling the `ctime` command. Think of the pair of parentheses as meaning, '*do this*'.
</div>

## Naming and Storing Values

Often the value returned by an operation will be used later on. Values can be stored for later use with the **assignment operator**. This has a different syntax that reminds the user that a value is being stored. Here's an example of a simple assignment:

In [51]:
x = 16

The command has stored the value `16` under the name `x`. The syntax is always the same: an equal sign (`=`) with a name on the left side and a value on the right.

Such stored values are called **objects**. Making an assignment to an object defines the object. Once an object has been defined, it can be referred to and used in later computations. Notice that an assignment operation does not return a value or display a value. Its sole purpose is to have the side effects of defining the object and thereby storing a value under the object's name.

To refer to the value stored in the object, just use the object's name itself. For instance:

In [52]:
x

16

# Computation on Variables

Doing a computation on the value store in an object is much the same (and provides and extremely rich syntax for performing complex calculations):

In [53]:
np.sqrt(x)

4.0

## Variable Names

You can create as many objects as you like and give them names that remind you of their purpose.
Some examples: `wilma`, `ages`, `temp`, `dog_houses`, `foo3`. There *are* some general rules for object names:

<br/>
<div class="alert alert-info" style="font-size: .8em;">
For the sake of readability, keep object names short. But if you really must have an object named something like `ages_of_children_from_the_clinical_trial`, feel free (it's just more typing for you later!).
</div>

* Use only letters and numbers and 'underscores' (`_`)
* Do **not** use spaces anywhere in the name (`Python` won't let you)
* A number cannot be the first character in the name
* Capital letters are treated as distinct from lower-case letters (*i.e.*, `Python` is *case-sensitive*)
    * the objects named `wilma`, `Wilma`, and `WILMA` are all different
* If possible, use an 'underscore' between words (*i.e.*, `my_object`)

## Objects

Objects can store all sorts of things, for example a range of numbers:

In [10]:
x = np.arange(1, 7)

When you assign a new value to an existing object, as just done to `x` above, the former values of that object is erased from the computer memory. The former value of `x` was `16`, but after the new assignment above, it is:

In [11]:
x

array([1, 2, 3, 4, 5, 6])

## Object Assignment

The value of an object is changed only via the assignment operator. Using an object in a computation does not change the value. For example, suppose you invoke the square-root operator on `x`:

In [12]:
np.sqrt(x)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974])

The square roots have been returned as a value, but this doesn't change the value of `x`:

In [13]:
x

array([1, 2, 3, 4, 5, 6])

If you want to change the value of `x`, you need to use the assignment operator:

In [14]:
x = np.sqrt(x)

<div class="alert alert-info" style="font-size: .8em;">
An assignment command like <code>x = np.sqrt(x)</code> can be confusing to people who are used to algebraic notation. In algebra, the equal sign describes a relationship between the left and right sides. So, $x = \sqrt{x}$ tells us about how the quantity $x$ and the quantity $\sqrt{x}$ are related. Students are usually trained to 'solve' such a relationship, going through a series of algebraic steps to find values for $x$ that are consistent with the mathematical statement (for $x = \sqrt{x}$, the solutions are $x = 0$ and $x = 1$). In contrast, the assignment command <code>x = np.sqrt(x)</code> is a way of replacing the previous values stored in <code>x</code> with new values that are the square-root of the old ones.
</div>

## Connecting Computations

The brilliant thing about organizing operators in terms of unput arguments and output values is that the output of one operator can be used as an input to another. This lets complicated computations be built out of simpler ones.

For example, suppose you have a list of `10000` voters in a precinct and you want to select a random sample of `20` of them for a survey. The `np.arange` operator can be used to generate a set of `10000` choices. The `np.random.choice` operator can then be used to select a subset of these values at random.

## Selecting Subsets

One way to connect the computations is by using objects to store the intermediate outputs:

In [15]:
choices = np.arange(1, 10000)
np.random.choice(choices, 20, replace=False) # Sample _without_ replacement

array([ 507, 1714, 6574, 5847, 9101, 2708, 6878, 5201, 1361, 8036,  828,
       9074, 2833, 1695, 5946, 9191, 3276, 8125, 3638, 7339])

## Passing Outputs

You can also pass the output of an operator *directly* as an argument to another operator. Here's another way to accomplish exactly the same thing as the above (note that the values will differ because we are performing a *random* sample):

In [16]:
np.random.choice(np.arange(1, 10000), 20, replace=False)

array([2911, 2508, 4752, 7974,   98, 6490, 6520,  913, 5288, 2517, 8688,
       1858, 2655, 2625, 4454, 5027, 7354, 1059, 9176,  978])

## Numbers and Arithmetic

The `Python` language has a concise notation for arithmetic that looks very much like the traditional one:

In [17]:
7. + 2.

9.0

In [18]:
3. * 4.

12.0

In [19]:
5. / 2.

2.5

In [20]:
3. - 8.

-5.0

In [21]:
-3.

-3.0

In [22]:
5.**2. # S ame as 5^2

25.0

## Complicating Things

Arithmetic operators, like any other operators, can be connected to form more complicated computations. For instance:

In [23]:
8. + 4. / 2.

10.0

<div class="alert alert-warning" style="font-size: .8em;">
The a human reader, the command `8+4/2` might seem ambiguous. Is it intended to be `(8+4)/2` or `8+(4/2)`?
The computer uses unambiguous rules to interpret the expression, but it's a good idea for you to use parentheses so that you can make sure that what you *intend* is what the computer carries out:
</div>

In [24]:
(8. + 4.) / 2.

6.0

## Mathematical Notation

Traditional mathematical notations uses superscripts and radicals to indicate exponentials and roots — *e.g.* $3^2$ or $\sqrt{3}$ or $\sqrt[3]{8}$. This special typography doesn't work well with an ordinary keyboard, so `Python` and most other computer languages uses a different notation:

In [25]:
3.**2.

9.0

In [26]:
np.sqrt(3.) # or 3.**0.5

1.7320508075688772

In [27]:
8.**(1./3.)

2.0

There is a large set of mathematical functions: exponentials, logs, trigonometric and inverse trigonometric functions, etc. Some examples:

<table border="0" style="font-size:.8em;">
<tr>
<th>Traditional/Math</th>
<th>Python</th>
</tr>
<tr>
<td>$e^2$</td>
<td><code>np.exp(2)</code></td>
</tr>
<tr>
    <td>$\log_{e}(100)$</td>
    <td><code>np.log(100)</code></td>
</tr>
<tr>
    <td>$\log_{10}(100)$</td>
    <td><code>np.log10(100)</code></td>
</tr>
<tr>
    <td>$\log_{2}(100)$</td>
    <td><code>np.log2(100)</code></td>
</tr>
<tr>
    <td>$\cos(\frac{\pi}{2})$</td>
    <td><code>np.cos(np.pi/2)</code></td>
</tr>
<tr>
    <td>$\sin(\frac{\pi}{2})$</td>
    <td><code>np.sin(np.pi/2)</code></td>
</tr>
<tr>
    <td>$\tan(\frac{\pi}{2})$</td>
    <td><code>np.tan(np.pi/2)</code></td>
</tr>
<tr>
    <td>$\cos^{-1}(-1)$</td>
    <td><code>np.acos(-1)</code></td>
</tr>
</table>

[pint]: https://pint.readthedocs.org/en/latest/
[quantities]: http://pythonhosted.org/quantities/
[units]: https://pypi.python.org/pypi/units/
[sympy.physics.units]: http://docs.sympy.org/latest/modules/physics/units.html
[etc]: http://conference.scipy.org/scipy2013/presentation_detail.php?id=174

## Scientific Notation

Numbers can be written in **scientific notation**. For example, the 'universal gravitational constant' that describes the gravitational attraction between masses is $6.67428 \times 10^{11}$ (with units meters-cubed per kilogram per second squared).

In the computer notation, this would be written as `6.67428e-11`.

<br/>
<div class="alert alert-warning" style="font-size: .8em;">
The `Python` language does not directly support the recording of units. Though we will learn about some *add-on* libraries that help with this later in the semester.
</div>

## Floating Points

Computer arithmetic is accurate and reliable, but it often involves very slight rounding of numbers. Ordinarily, this is not noticeable. However, it can become apparent in some calculations that produce results that are (near) zero. For example, mathematically, $sin(\pi) = 0$, however, the computer does not duplicate the mathematical relationship exactly:

In [28]:
np.sin(np.pi)

1.2246467991473532e-16

Whether a number like this is properly interpreted as 'close to zero' depends on the context and, for quantities that have units, on the units themselves.

## Special 'Numbers'

There are several 'special' numbers in the `Python` world; two of which are `inf`, which stands for $\infty$ (infinity), and `nan`, which stands for 'not a number' (nan results when a numerical operation isn't define), for instance:

In [29]:
np.float64(1.) / 0.

/Users/carsonfarmer/miniconda3/envs/space-time/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in double_scalars
  if __name__ == '__main__':


inf

In [30]:
np.float64(0.) / 0.

/Users/carsonfarmer/miniconda3/envs/space-time/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in double_scalars
  if __name__ == '__main__':


nan

<div class="alert alert-warning" style="font-size: .8em;">
Mathematically oriented readers will wonder why <code>Python</code> should have any trouble with a computation like $\sqrt{-9}$; the result is the imaginary number $3\jmath$ (imaginary numbers may be represented by a $\jmath$ or a $\imath$, depending on the field). <code>Python</code> works with complex numbers, but you have to explicitly tell the system that this is what you want to do. To calculate $\sqrt{-9}$ for example, simply use <code>np.sqrt(-9+0j)</code>.
</div>

## Types of Objects

Most of the examples used so far have dealt with numbers. But computers work with other kinds of information as well: text, photographs, sounds, data-sets\*, and so on.

<br/>
<div class="alert alert-info" style="font-size: .8em;">
\* In `Python`, data frames are not 'built in' as part of the basic language, but the excellent [`pandas`](http://pandas.pydata.org/) library provides data frames and a whole slew of other functionality for researchers doing data analysis with `Python`. We will be learning more about `pandas` coming up.
</div>

## Types...

The word **type** is used to refer to the *kind* of information. Modern computer languages support a great variety of types. It's important to know about the types of data because operators expect their input arguments to be of specific types. When you use the wrong type of input, the computer might not be able to process your command.

## A Note on Strings

Whenever you refer to an object name, make sure that you don't use quotes. For example, in the following, we are first assigning the string `"python"` to the `name` object, and then returning (and printing automatically) the `name` object.

In [31]:
name = "python"
name

'python'

Inputting the *string* **doesn't** refer to an object: it will merely 'print' the text itself:

In [32]:
"name"

'name'

## Names vs Strings

Similarly, if you omit the quotation marks from around the text, `Python` will treat it as an object name and will look for *that* named object.

For instance, here we 'lookup' the value contained in a `python` object and insert that value into `name`:

In [33]:
name = python

NameError: name 'python' is not defined

## Oops!

As it happens, there was no object named `python` because it had not been defined by any previous assignment command. So, the computer generated an error.

And on that note... its time to move on!